-- 1. Create the stats table if it doesn't exist
create table if not exists public.stats (
  id bigint generated by default as identity primary key,
  total_sponsored_kids bigint default 7450
);

-- 2. Insert initial row if empty
insert into public.stats (id, total_sponsored_kids)
select 1, 7450
where not exists (select 1 from public.stats);

-- 3. Enable Realtime for this table
alter publication supabase_realtime add table public.stats;

-- 4. Create the Atomic Increment Function (RPC)
create or replace function increment_counter(amount int)
returns void
language plpgsql
as $$
begin
  update public.stats
  set total_sponsored_kids = total_sponsored_kids + amount
  where id = 1;
end;
$$;
